---
# tasks file for ansible/roles/docker
- name: Install device-mapper-persistent-data # nom de la tâche
  yum: # module qui installe la dernière version de device-mapper-persistent-data
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2 # nom de la tâche
  yum: # module qui installe la dernière version de lvm2
    name: lvm2
    state: latest

- name: Add repo docker # nom de la tâche
  command: # exécute la commande pour ajouter le répertoire d'installation de Docker dans l'installateur
    cmd: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker # nom de la tâche
  yum: # module qui installe Docker
    name: docker-ce
    state: present

- name: Install python3 # nom de la tâche
  yum: # module qui installe Python 3
    name: python3
    state: present

- name: Install Docker with Python 3 # nom de la tâche
  pip: # installe la librairie docker dans Python
    name: docker
    executable: pip3
  vars: # précise dans Ansible où se trouve Python
    ansible_python_interpreter: /usr/bin/python3

- name: Make sure Docker is running # nom de la tâche
  service: # lance Docker pour s'assurer qu'il est bien installé
    name: docker
    state: started
  tags: docker