name: test-backend

# Lancement des tests à chaque push/pull sur les branches main et develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:

# Définition des tests à faire
jobs:
    # Tests sur le backend
    test-backend:
      runs-on: ubuntu-22.04 # les tests se lancent sur une machine virtuelle ubuntu
      steps:
        # Clone du code sur le runner pour le compiler et le tester
        - name: Checkout code
          uses: actions/checkout@v2.5.0
  
        # Mise en place de l'environnement JDK 17
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        
        # Compilation de l'application avec Maven et vérification de la qualité du code avec Sonar
        - name: Build and test with Maven and SonarCloud
          run: mvn -B verify sonar:sonar -Dsonar.projectKey=Setsuna8522_devops -Dsonar.organization=setsuna8522 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN}} -f ./backend/pom.xml